### PR TITLE
Flex block palette

### PR DESCRIPTION
**Pull request by towerofnix**
Oops I think I branched off of the wrong branch :D

Here's a screenshot:

Screenshot

EDIT: yeah totally branched off the wrong branch; idk how to fix. @Firedrake969 explain?

### CODE REVIEW

**Comment by matthewr6** [comment]
ogod

**Comment by matthewr6** [comment]
you should branch off `gh-pages`
luckily you didn't make a whole lot of changes, so maybe just remember them and make the same changes again?

**Comment by towerofnix** [comment]
yep yep, not hard to make the changes again lol

**Comment by matthewr6** [comment]
thanks
gitter please

**Pull request closed without merging**
