### PR TITLE
Rework blocks

### PR DESCRIPTION
**Pull request by mrjacobbloom**
see #248 

This implements a Blockly-like system of objects for blocks, scripts, and block attributes. I also re-wrote json2html to take advantage of the new system. There's some work to be done but this is a start and I'd like to get your thoughts before I move forward.

to do:
- [x] make it work for CSS files (I haven't even tried a CSS file since I started rewriting)
- [x] better coordinate system - it's still using awkward JS offsets and stuff, I wanna see if I can make this more robust
- [x] test tutorials - idk if I broke them
- [x] update file import/export

Still to do:
- [x] limit when the context menu appears (e.x. in the palette)
- [x] CSS files should begin with an example selector
- [x] the first input in a rule block should have a dropdown with css properties
- [x] rename code things so they have better names
- [x] CSS->JSON only exports the blocks that are attached to the stack. Export the loose ones too.

### CODE REVIEW

**Comment by matthewr6** [comment]
@Airhogs777 I assume I (and others) shouldn't test and merge this until all of those boxes are checked?

**Comment by mrjacobbloom** [comment]
feel free to start playing with it, but don't merge it quite yet

**Comment by matthewr6** [comment]
@Airhogs777 Could you get this on a branch of the main repo (ElementalCode/elemental) so I can pull/branch/push it?  (no rush since I won't be able to for a while anyways)

**Comment by mrjacobbloom** [comment]
That'll take some git-fu but I'll try

**Comment by mrjacobbloom** [comment]
ok I figured out how to push to this repo without breaking anything, but I'll keep sending new commits to the branch on my repo, so remind me to push to here if you want to test a newer version

**Comment by matthewr6** [comment]
Awesome, thanks

**Comment by iamunknown2** [comment]
I've tested the first tutorial, and something probably broke (was it always the case tho?):
Tutorial 1 glitch
The console doesn't seem to throw up any JS errors either...

**Comment by iamunknown2** [comment]
I've tested out the 2nd tutorial, and it looks like there are a few bugs:
Glitches

1. Where did the attribute value input go?
2. The image doesn't seem to show up.

I might be able to help out.

**Comment by iamunknown2** [comment]
The first bug seems to be due to the fact that the element is collapsed (height).
Applying `display: inline-flex;` (overriding `display: inline-block`) to `span.attr-holder` seems to do the trick (and also fixes uneven inputs as well!)
I've already made a PR [here](https://github.com/ElementalCode/elemental/pull/252).

**Comment by iamunknown2** [comment]
Wait, where's json2html (since block2json.js exists already)?

**Comment by mrjacobbloom** [comment]
> Applying display: inline-flex; (overriding display: inline-block) to span.attr-holder seems to do the trick (and also fixes uneven inputs as well!)

Thanks for pointing that out! I'll make that change manually, since idk how to use PRs for other PRs. and it's a one-line fix.

> Wait, where's json2html (since block2json.js exists already)?

Those functions are called blockTreeToHTML and blockTreeToCSS

**Comment by iamunknown2** [comment]
Also, the image blocks seem to work fine perfectly - it seems to be limited only to the tutorial.

**Comment by iamunknown2** [comment]
Another glitch: When you take blocks out and put them back into the body, they reverse in order.

**Comment by mrjacobbloom** [comment]
> Also, the image blocks seem to work fine perfectly - it seems to be limited only to the tutorial.

I'm working on that, making the tutorials work is on the to-do list

> Another glitch: When you take blocks out and put them back into the body, they reverse in order.

Do you have a specific example? Possibly in gif form?

I'm also currently working on some issues with file import and switching between open files, so don't be surprised if you find issues there

**Comment by iamunknown2** [comment]
> Do you have a specific example? Possibly in gif form?

I don't, but I figured out that the glitch arises around line 475 in blocks.js - it seems that the virtually all new connections' types (besides connecting two blocks outside the body tag) are `nullWrapperContent`, leading the child to be inserted at the beginning instead of at the end.

**Comment by mrjacobbloom** [comment]
I'm not seeing that---again, a gif/video of the issue would really help

**Comment by iamunknown2** [comment]
> I'm not seeing that---again, a gif/video of the issue would really help

OK, [here](https://youtu.be/r66NQ07nkU8).

I've made a fix (reversing the `kids` list around line 471) for the glitch (committed to this branch, but not pushed yet - waiting for confirmation).

**Comment by matthewr6** [comment]
It may be better to not report glitches until the PR is actually complete since incomplete things won't be perfect

**Comment by mrjacobbloom** [comment]
It may be better to not report glitches until the PR is actually complete since incomplete things won't be perfect

^^
reports are okay, but I can't keep merging in these fixes

**Comment by mrjacobbloom** [comment]
okay I think I've got all the major parts working. @Firedrake969 I've pushed to this repo so you can test

**Comment by mrjacobbloom** [comment]
I merged in @iamunknown2's new changes from #251 -- note that intro.js doesn't play nice with the scrollable workspace (but that's an issue for a separate PR)

**Comment by mrjacobbloom** [comment]
there's still this issue where switching back and forth between a css file and another file a few times corrupts the css file, I'm trying to figure out what's up with that but I haven't got it yet

EDIT: resolved that

**Comment by mrjacobbloom** [comment]
I updated the OP to-do list with some stuff that still needs to get done. But besides those I believe it's fully functional so feel free to start testing/reviewing how things are structured. I might wanna rename some things

**Comment by mrjacobbloom** [comment]
ok I finished the to-do list. All commits have been pushed to this repo for testing

**Comment by mrjacobbloom** [comment]
hold up testing that latest commit, I just broke something

EDIT: fixed

**Comment by mrjacobbloom** [comment]
@Firedrake969 @iamunknown2 what are you looking for in terms of the spec? This project isn't using JSDoc -- would a page on the wiki work?

And I'd really like everyone's feedback on this--is there any way it could work better, do you see any bugs or other problems? etc @ElementalCode/programmers

**Comment by mrjacobbloom** [comment]
http://google.github.io/styleguide/javascriptguide.xml?showone=Closures#Closures why is garbage collection literal garbage

**Comment by mrjacobbloom** [comment]
https://xkcd.com/1296/

**Comment by benajaero** [comment]
> snipped by firedrake

**Comment by mrjacobbloom** [comment]
I, uh... yes correct

**Comment by mrjacobbloom** [comment]
it's so long

**Comment by benajaero** [comment]
You've done a lot...

**Comment by mrjacobbloom** [comment]
lol fair enough

**Comment by bates64** [comment]
May want to fix circleci.

**Comment by matthewr6** [comment]
@lightblub it's fine probably
image

**Comment by iamunknown2** [comment]
Wait, what happened to `display: inline-flex;` for `.attr-holder`? The attribute value input is missing again.

**Comment by mrjacobbloom** [comment]
> Wait, what happened to `display: inline-flex;` for `.attr-holder`?

[it's still there?](https://github.com/ElementalCode/elemental/pull/249/files#diff-8bd44c98b86b61de29be357e8933e495R175)

**Comment by Firedrake969** [comment]
ok so this is why we should have a single repo and only branch off the main repo

**Pull request closed without merging**
