### PR TITLE
Replace “breadfish.gif” With a Constant

### PR DESCRIPTION
**Pull request by mrjacobbloom**
In case we want to change it in the future

### CODE REVIEW

**Comment by matthewr6** [comment]
all hail breadfish

**Comment by PullJosh** [comment]
Also... It being `breadfish.gif` for the text block is *really* confusing.

**Comment by matthewr6** [comment]
It's just `breadfish` now I think

**Comment by mrjacobbloom** [comment]
I made it `breadfish` for now, but only so I could see that it successfully changed everywhere. Now we can argue about what it should be and easily change it all in one place

**Pull request merged**
