### PR TITLE
Block editor

### PR DESCRIPTION
**Pull request by matthewr6**
@PullJosh @quat1024 @an-OK-squirrel @Rumanti  @liam4 
Anyone can merge once they look through my code and make sure stuff works.

### CODE REVIEW

**Comment by PullJosh** [comment]
I'll take a look.

**Comment by matthewr6** [comment]
Cool, thanks.
What it has is multiple files (switching between and addition of), and saving locally.

**Comment by PullJosh** [comment]
n00b question: how do I get the changed version locally?

I have gh for windows/desktop (new version), but I can use cmd line if you tell me exactly what to type. :3

**Comment by matthewr6** [comment]
Depends... don't you have block-editor already?  If so, just hit Sync

**Comment by PullJosh** [comment]
*facepalm*

**Comment by matthewr6** [comment]
so... it work?

**Comment by PullJosh** [comment]
Yeah.

**Comment by matthewr6** [comment]
xD
What about the actual code things?

**Comment by PullJosh** [comment]
Looks great! A few bugs to work out, but I think it's good enough to merge. :)

Stuff I noticed right away:
1) Ugly (not really a bug)
2) Can create files with no name
3) Ignores file extensions

... That's actually about it.

Oh, and you should probably be allowed to resize things (why'd you remove interact.js?)

It's a major step forward, but could still use some work. :)
(Once you justify or fix the interact.js removal, I'll merge.)

**Comment by PullJosh** [comment]
Still... pretty impressive.

**Comment by matthewr6** [comment]
@PullJosh  - not sure what you mean about interact.js - it's there but I just moved it, so you can still resize things.  And yeah it definitely needs work - not the finished product by any means :P

**Comment by PullJosh** [comment]
Weird... I can't drag the vertical divider (vertical line which you drag left & right) any more.

Saw that the line was removed and assumed you got rid of the script (failing to notice, of course, the new vendor/)

On Chrome, btw.

**Comment by matthewr6** [comment]
It works if you pull it to the right or to the left very slowly or with your mouse around the bottom of the page, because the iframe messes things up for some reason

**Comment by PullJosh** [comment]
Nope. :/

**Comment by matthewr6** [comment]
Works for me...
http://prntscr.com/8855rc

**Comment by PullJosh** [comment]
Although I had noticed the iframe thing before... Maybe set `pointer-events: none;` on iframe when dragging?

Anyway, what version of Chrome?

**Comment by matthewr6** [comment]
Latest.
44.0.2403.157 m

**Comment by PullJosh** [comment]
Same... windows?

**Comment by PullJosh** [comment]
Either way, probably worth merging.

**Comment by matthewr6** [comment]
Win10

**Comment by PullJosh** [comment]
Ah, I'm on 8.1... I'll make a new issue for all this.

Should I merge?

**Comment by matthewr6** [comment]
Not yet... if I don't have a solution in 10 minutes from this post, go ahead

**Comment by PullJosh** [comment]
k

**Comment by matthewr6** [comment]
Ok, go ahead and merge

**Comment by PullJosh** [comment]
:)

**Comment by matthewr6** [comment]
Awesome

**Pull request merged**
