### PR TITLE
Fix dragged blocks hidden in the blocks area

### PR DESCRIPTION
**Pull request by mrjacobbloom**
See #216 

It turns out it wasn't actually a z-index issue, it was an overflow issue 📦

### CODE REVIEW

**Comment by mrjacobbloom** [comment]
The rest of the PRs should be fine to merge

**Comment by towerofnix** [comment]
FYI instead of posting "See #216" you could post "Fixes #216", then GitHub will automatically close #216 for you when this pull request gets merged!

**Comment by PullJosh** [comment]
That's actually super cool!

**Comment by mrjacobbloom** [comment]
> FYI instead of posting "See #216" you could post "Fixes #216", then GitHub will automatically close #216 for you when this pull request gets merged!

maybe I /wanted/ to close it manually. Did you ever think of that? Huh?????>?>>>>>???????

jk that's pretty cool 💃

**Pull request merged**
