### PR TITLE
Add blocks, rename & organize

### PR DESCRIPTION
**Pull request by ghost**
I added 3 new heading blocks.
I renamed the name of "div" to "division" since this is more human readable.
I (kind of) organized the filter.blocks array.

### CODE REVIEW

**Comment by matthewr6** [comment]
Not merging yet - will have to set up some block stds

**Comment by matthewr6** [comment]
Eg what classes they should have

**Comment by ghost** [comment]
?

**Comment by matthewr6** [comment]
#73

**Pull request merged**
