### PR TITLE
Added offset to fix pushed-up problem...

### PR DESCRIPTION
**Pull request by iamunknown2**
…,  but helper layer in intro.js is now off for a tutorial step when the offset is activated.

### CODE REVIEW

**Comment by mrjacobbloom** [comment]
oh god this PR is dependent on #249 why is everything so complicated

**Comment by iamunknown2** [comment]
> oh god this PR is dependent on #249 why is everything so complicated

It isn't that hard to merge - there's a merge button right on this page...

**Comment by mrjacobbloom** [comment]
>> oh god this PR is dependent on #249 why is everything so complicated

> It isn't that hard to merge - there's a merge button right on this page...

yeah but if we merged this before 249 then it would probably break everything

**Comment by iamunknown2** [comment]
> yeah but if we merged this before 249 then it would probably break everything

I've tested a merge of my branch with gh-pages locally, and there doesn't seem to any merge conflicts.

**Comment by mrjacobbloom** [comment]
okay good, the thing that was scaring me was
screen shot 2017-04-20 at 8 21 58 am
it's set to merge into the branch rework-blocks... remember that the branch #249 is merging is on Airhogs777/elemental, and the rework-blocks branch on this repo is just for testing

we'll just have to make sure to manually merge it with gh-pages instead of hitting the "merge PR" button which will probably send it to rework-blocks

**Comment by mrjacobbloom** [comment]
see this is what it actually looks like because it's based on the changes made in my PR

**Comment by iamunknown2** [comment]
What's wrong with merging this into 249?

**Comment by mrjacobbloom** [comment]
Because 249 isn't merging in ElementalCode/elemental:rework-blocks, it's merging in Airhogs777/elemental:rework-blocks

**Comment by matthewr6** [comment]
ok so this is why we should have a single repo and only branch off the main repo

**Comment by mrjacobbloom** [comment]
true

but also merging a PR into another PR feels wrong

**Comment by matthewr6** [comment]
@Airhogs777 can you talk on discord rn

**Comment by matthewr6** [comment]
@Airhogs777 Ok, PRs fixed and stuff.  I feel like merging a branch into another non-master branch is fine via PR provided it's someone who's trying to make changes to your stuff - at which point it's up to you to determine whether to merge it

**Comment by mrjacobbloom** [comment]
Sorry I'm at work and just saw this. Thanks for fixing this

**Pull request closed without merging**
