### PR TITLE
Added offset to fix pushed-up problem, but helper layer in intro.js i…

### PR DESCRIPTION
**Pull request by matthewr6**
…s now off when the offset is activated

Previously #257

### CODE REVIEW

**Review by mrjacobbloom — CHANGES_REQUESTED** [review]
I'm still having the same issue after this change:

output

**Comment by iamunknown2** [comment]
> I'm still having the same issue after this change:

I've went back to my branch - it seems like it bounces up and down on Chromium but not on Firefox. Weird.

Anyway, I've pushed a commit that may fix your problem (my original code judging when to show the offset was pretty sketchy, TBH).

**Comment by mrjacobbloom** [comment]
It still functions the same for me with your new commit :(

**Comment by iamunknown2** [comment]
Huh, weird - it functions pretty well on my machine.

**Comment by mrjacobbloom** [comment]
I pushed a commit to rework-blocks that fixes this.

**Pull request closed without merging**
