### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by matthewr6**
so now this is actually a functional, but ugly, site :D

### CODE REVIEW

**Comment by an-OK-squirrel** [comment]
I can haz  button?

**Comment by matthewr6** [comment]
you can haz

**Comment by matthewr6** [comment]
thanks

**Comment by towerofnix** [comment]
How does use?

**Comment by PullJosh** [comment]
How does grammar?

**Comment by an-OK-squirrel** [comment]
How does cats?

**Comment by PullJosh** [comment]
Very.

**Comment by an-OK-squirrel** [comment]
How does cacti?

**Comment by matthewr6** [comment]
not

**Pull request merged**
