### PR TITLE
Block editor

### PR DESCRIPTION
**Pull request by matthewr6**
giant update - if someone says that I can, I'll do the merge stuff

### CODE REVIEW

**Comment by PullJosh** [comment]
Fine by me.

**Comment by PullJosh** [comment]
But make sure you either have a backup or can undo the change, just in case.

**Comment by matthewr6** [comment]
Remember the whole point of Git :P

**Comment by matthewr6** [comment]
dangit that was messy

I merged in a weird way

**Comment by PullJosh** [comment]
@Firedrake969 It's hard to remember something you never figured out. :P

**Comment by an-OK-squirrel** [comment]
It's a version control system. That what makes it different that file hosting :p

**Comment by PullJosh** [comment]
I know. I was joking. :P

**Comment by an-OK-squirrel** [comment]
Yeah. I wonder what people mean when they use /s. Good thing you didn't use it

/s

**Pull request closed without merging**
