### PR TITLE
Block editor intuitive trash

### PR DESCRIPTION
**Pull request by iamunknown2**
Added Khan Academy-like intuitive trash which shows up in the menu whenever you move something.

You may want to change the quality of the trash images.

~~Also changed all the indentation into tabs. I don't care if you like them or not - just keep it consistent (I found some 2-space indents on the **same line** with 4-space indents)~~ Oh no - let me replace all tabs with two-space indentations. My bad for not reading the guidelines again :package:

### CODE REVIEW

**Comment by matthewr6** [comment]
Could you change the indent back to normal?  It makes it super hard to read the diff

**Comment by iamunknown2** [comment]
@Firedrake969 OK but I thought that you were supposed to do 2-space-indents (which was not what it was supposed to be).

**Comment by matthewr6** [comment]
4-space.  (that's what I've been doing and I've written like half the editor code :P)

**Comment by iamunknown2** [comment]
OK

**Comment by matthewr6** [comment]
Also idk why we have `block-editor as an intermediate, I'm going to close this and move the PR over to gh-pages

**Pull request closed without merging**
