### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### ElementalCode/Elemental now has a Chat Room on Gitter

@Firedrake969 has just created a chat room. You can visit it here: [https://gitter.im/ElementalCode/Elemental](https://gitter.im/ElementalCode/Elemental?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/ElementalCode/Elemental?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by matthewr6** [comment]
Should we?

**Comment by quat1024** [comment]
Yeah sure, why not. Pretty cool that a little robot does that for us huehue. Let's be nice to it

**Comment by quat1024** [comment]
Yuck, it's in a weird spot. I'll fix it

**Comment by matthewr6** [comment]
ok

**Pull request merged**
