### PR TITLE
Block editor

### PR DESCRIPTION
**Pull request by matthewr6**
or @quat1024 or @an-OK-squirrel or someone else

### CODE REVIEW

**Comment by PullJosh** [comment]
Has a few minor issues, but worth merging.

**Comment by matthewr6** [comment]
What are the issues?  (Besides the file name thing and ugly prompt)

**Comment by PullJosh** [comment]
FYI, issues are as follows:
1) Right-click a block and then click on the page preview (or anywhere that doesn't have a custom context menu, for that matter). Ctx menu won't go away until you click back in the block area
2) Can right-click on the background surrounding the blocks. Which is weird.

**Comment by matthewr6** [comment]
Ok should be easy fixes

**Comment by an-OK-squirrel** [comment]
good morning

**Comment by PullJosh** [comment]
good mythical morning. :)

**Comment by an-OK-squirrel** [comment]
Too busy with school for gmm

**Comment by PullJosh** [comment]
*gasp*

**Comment by an-OK-squirrel** [comment]
also playing too much video games :package:

**Comment by quat1024** [comment]
"school" :^)

speaking of school i'm at school RIGHT NOW :astonished:

**Comment by an-OK-squirrel** [comment]
Same

**Pull request merged**
