### PR TITLE
Block2json

### PR DESCRIPTION
**Pull request by matthewr6**
start with blocks to json (HTML only)
it works, but onload right now.  Won't be hard to change to update when an event happens, though

### CODE REVIEW

**Comment by an-OK-squirrel** [comment]
all checks have failed D:

**Comment by matthewr6** [comment]
Lol there were no checks to fail

**Comment by PullJosh** [comment]
No?
image

**Comment by matthewr6** [comment]
Nope, but I misworded that.
http://prntscr.com/82b2rb
CircleCI is only for the Django stuff anyways

**Comment by PullJosh** [comment]
Oh, I see.

**Comment by matthewr6** [comment]
Could someone merge it?

**Comment by PullJosh** [comment]
I'll click the button if you promise it won't break things.

**Comment by matthewr6** [comment]
It won't.

**Comment by matthewr6** [comment]
Thanks

**Pull request merged**
