### PR TITLE
Trash can

### PR DESCRIPTION
**Pull request by PullJosh**

### CODE REVIEW

**Comment by PullJosh** [comment]
fail fail fail not to master

**Comment by matthewr6** [comment]
WOAH THERE

**Comment by PullJosh** [comment]
you can do the git things

**Comment by matthewr6** [comment]
k also what http://prntscr.com/8705wm we can fix it later tho

**Comment by PullJosh** [comment]
You mean the scroll bars?

**Comment by matthewr6** [comment]
yes and ok merged

**Pull request closed without merging**
