### PR TITLE
Committed new frontpage stuff

### PR DESCRIPTION
**Pull request by PolyEdge**
This is a pull request for the the new frontpage. Firedrake, I need approval.

Also, some of the new stuff like helpers.css was sass being glitchy and converting everything in the directory :package: 

If you want something changed, clone the new-frontpage branch and make your changes, push, or ask me.

### CODE REVIEW

**Comment by matthewr6** [comment]
I'll check it out today

**Comment by matthewr6** [comment]
# **_I LOVE THIS.**_

**Comment by PolyEdge** [comment]
Thanks :)

**Comment by PolyEdge** [comment]
Wait, some of the stuff is using my domain still...

I'll fix

**Comment by matthewr6** [comment]
k

**Pull request merged**
