### PR TITLE
Quick Fix

### PR DESCRIPTION
**Pull request by ghost**
Fixed issue when resizing the leftSide element, where when you resize it the filePane wouldn't resize with it.

### CODE REVIEW

**Comment by matthewr6** [comment]
Could you squash those commits and/or make them more descriptive?

**Comment by towerofnix** [comment]
@Firedrake969 Can't that be done when you merge?

**Comment by ghost** [comment]
I'm not sure how to do that. I only added one line in the end at the last commit (line 18) and that's all it needs

**Comment by matthewr6** [comment]
@liam4 Squashing commits?  It'd probably be harder

@Flame2057 did you use the GitHub online editor to do this?

**Pull request closed without merging**
