### PR TITLE
Cleaned up some css and more scratch like layout

### PR DESCRIPTION
**Pull request by robinp7720**
mainly moved everything to scss and separated out some of the colour styles

### CODE REVIEW

**Comment by PullJosh** [comment]
nope

**Comment by matthewr6** [comment]
Lol

**Comment by an-OK-squirrel** [comment]
What's wrong with this?

**Comment by PullJosh** [comment]
We didn't make it.

**Comment by an-OK-squirrel** [comment]
:/ What's  wrong with that? This is github.

**Comment by matthewr6** [comment]
We had issues with him before, so he's basically not allowed any more,

**Comment by an-OK-squirrel** [comment]
Butbif I made the same PR, what would you  do?

**Comment by PullJosh** [comment]
You wouldn't.

**Comment by an-OK-squirrel** [comment]
huh ok

**Comment by an-OK-squirrel** [comment]
But why not? He's actually helpin for once

**Comment by PullJosh** [comment]
It's not just about code. By accepting a PR from him, we're inviting him back into the group (which could cause issues in the future.)

**Comment by an-OK-squirrel** [comment]
:/ kk

**Comment by an-OK-squirrel** [comment]
@robinp7720 I tried

**Pull request closed without merging**
