### PR TITLE
Block editor

### PR DESCRIPTION
**Pull request by matthewr6**
super fancy js

### CODE REVIEW

**Comment by matthewr6** [comment]
people...
@quat1024 @an-OK-squirrel

**Comment by PullJosh** [comment]
I'll merge if you want.

**Comment by matthewr6** [comment]
Yes please

**Comment by matthewr6** [comment]
merge? please?

**Comment by an-OK-squirrel** [comment]
Done

**Comment by PullJosh** [comment]
You're welcome, @Firedrake969.

**Comment by an-OK-squirrel** [comment]
xD

**Pull request merged**
