### PR TITLE
Fixed delay issue

### PR DESCRIPTION
**Pull request by iamunknown2**
Replaced keydown event with input event

### CODE REVIEW

**Comment by matthewr6** [comment]
Will check out soon unless someone tests it before me

**Comment by iamunknown2** [comment]
@Firedrake969 I have tested it this time, and it seems to work. However, glitches may arise from this change (maybe a few scripts that rely on keydown conflict with this one?)

**Comment by matthewr6** [comment]
Have you found any yourself?

**Comment by iamunknown2** [comment]
@Firedrake969 Nope, but probably because I haven't searched for them in the first place :package:

**Comment by matthewr6** [comment]
Ok I'll try to check tomorrow

**Comment by matthewr6** [comment]
Doesn't fix the issue.

**Comment by matthewr6** [comment]
Oops, my bad.  jk

**Pull request merged**
