### PR TITLE
Update GH Pages?

### PR DESCRIPTION
**Pull request by towerofnix**
So.. yes.

### CODE REVIEW

**Comment by towerofnix** [comment]
I'll let you merge this @Firedrake969 haha.

**Comment by an-OK-squirrel** [comment]
I can haz merge?

**Comment by an-OK-squirrel** [comment]
@Firedrake969 please delete squirrel-makes-a-af0askfiajf;a

**Comment by matthewr6** [comment]
ok

**Comment by an-OK-squirrel** [comment]
`</offtopic>`

**Pull request merged**
