### PR TITLE
Ui

### PR DESCRIPTION
**Pull request by matthewr6**
Integrate UI with Django urls and such.

### CODE REVIEW

**Comment by PullJosh** [comment]
Almost done with 0.0.3, if you want to wait.

**Comment by matthewr6** [comment]
Sure thing!  Did you see the mixin I added?

**Comment by PullJosh** [comment]
I did. Thanks for the help. ;)

**Comment by matthewr6** [comment]
Yup :)
I'll set up stuff in the `dev` branch later so you can run it locally.

**Comment by PullJosh** [comment]
Please don't randomly delete my branches without notice.

Thanks. :)

**Comment by matthewr6** [comment]
Yeah, too used to deleting once the branch is merged.  Could you work in the dev branch now, though?  It'll keep everything cleaner.

**Comment by PullJosh** [comment]
Hmm... I'd really rather not.

Too be honest, I'm considering making an entirely new repo just for front-end things. That way it isn't obscured byback-end stuff.

**Comment by matthewr6** [comment]
It'd just be harder to copy and paste, and it's not exactly "obscured" in the first place.
Generally, you'll want to keep everything in the same place, and at least learn to not get completely confused by stuff you're not working with.

**Comment by PullJosh** [comment]
I couldn't find it until you specifically linked to the folder the UI was in (in a seperate issue). I'd say that's pretty hard to find.

**Comment by matthewr6** [comment]
I'll make a symlink.

**Comment by PullJosh** [comment]
Oh, that'll be good!

**Comment by PullJosh** [comment]
Borderline good enough to warrent keeping everything in one repo.

**Comment by matthewr6** [comment]
heh

**Comment by PullJosh** [comment]
Borderline being the key word.

**Comment by matthewr6** [comment]
It's that hard to navigate a file system?  :/

**Comment by quat1024** [comment]
Well, hiding the actually relevant files in /projects/templates/irrelevant_folder_name/temp/junk4/backend/frontend, and leaving all your junk files everywhere else in the repo... well, doesn't sound like the best way to go about it

**Comment by matthewr6** [comment]
Don't exaggerate.
apps/projects/templates
The other files aren't "junk", lol

**Comment by quat1024** [comment]
> The other files aren't "junk", lol

They are to _everyone_ except your backend group

**Comment by matthewr6** [comment]
So as a web developer you can be safely quarantined where you feel at home?  Not really - web development isn't about all one or the other.  It's like developing on OpenSprites but asking for no PHP in the html file xD

Anyways.  Please, just figure out how to navigate up three directories.  It's not hard.  I've already ignored the best practices in Django just so that you can develop in a little more peace...

**Comment by matthewr6** [comment]
actually this deserves a new comment...

you know what
just develop in another branch or something and I'll copy/paste it in so we use the best practices.

**Comment by robinp7720** [comment]
What's wrong with separating the back end and the front end  into two separate repos?

Also, to me it seams your python code is extremely dis-organized.

Anyways, to an earlier comment you left me, django is a python templating engine. If you think because I mainly have php projects that I don't know python, you are seriously mistaking. Php also has millions of templating engines. Python first off is a really easy language to learn. It was the second language I ever learned.

What happened to the rest api? You close the issue and said it was done but I still see django being used as a templating engine. The rest api should be a rest api and that's it. 

If half of the group can't cope with the other half, there is no point in trying to keep this alive. I've helped two other projects but none of them actually wanted to agree and one person kept overpowering everyone else. If you firedrake would actually accept other peoples ideas instead of saying "good idea" and ignoring it past that this project would defiantly have a future.

The back end is current absolutely unnecessary without even having the project finished, which is, if you haven't forgotten a block based html and CSS editor. Or have I gotten it wrong and you want to make a backend to a non existent block editor?

Sorry if I sound mean or anything but its the truth. I've been with enough dev groups to know exactly what's going to happen next.

**Comment by matthewr6** [comment]
Nothing - I said I'd just combine them!  If you think my code is messy, tell me how and I will fix it.  I'm not sure, but it seems you're just trying to harass what I'm doing but with nothing solid to back yourself up.

That's kind of irrelevant, but django isn't just a templating engine. If I wanted that, I'd use jinja2. 
PHP doesn't have "millions" of templating engines, and being a really easy language doesn't make it any less powerful.  An ad hominem attack is completely pointless.  I don't care what anyone knows - rather, I care that they can make what they know and learn _work together_.

Doesn't seem like its me overpowering - I'm just trying to keep everything organized.  Rather, don't tell us "it should be X and that's it".  Again, it's definitely not me trying to force things on everyone, lol.

Then start working on it with us...  Once you begin doing stuff or have proven experience with us, you have the right to complain.

We'll see about that.  I'm kind of interested in what sort of stuff you've done, though - links to the GH repos/organizations?

**Comment by BookOwl** [comment]
@robinp7720, your are not being mean, you are telling the truth! As far as I can tell, the back end is just going to be for saving projects. That's it. There was some talk about having a publicly shareable projects and forums, but since we didn't want to get sued if somebody shared a project that gave you a virus or have to moderate forums, that seemed to stop. If we can't resolve this front end/back end issue, this project is going to self-destruct in a horrible way! People have already been fighting in the issues and on our scratch forum over this. Here is my plan for how to resolve it:
1. Host the site on GitHub pages. Yes, we will not be able to run django, or any other back end code, but if we do the rest of my plan, we won't need it. This will also mean that our site won't be down for six (6!) hours every day!
2. For project storage, use something like Microsoft Azure Mobile services for storing the projects. We could use the JS zip file library ( I can't remember the name ) that somebody was talking about to create the zip file, and use Azure's REST API to send and retrieve the projects. 
@Firedrake969, I'm sorry, but unless we are adding more to the back end then just project storage, I don't think we can justify using it.

**Comment by matthewr6** [comment]
This is how we can easilyresolve it:
1.  GH pages editor for those who insist on "purity"
2.  Actual webapp for those who want to save/share (after manual approval) projects.

If all you guys want to do is frontend, go wild - I'll just incorporate everything into the webapp.  Don't worry about it, and make a separate branch or repository.

Any problems with that plan?  Again, I will reiterate - you do **NOT** need to even touch the branch/repo with the backend.  I and possibly **init** will handle that.

**Comment by BookOwl** [comment]
@Firedrake969, I am not trying to be a "purist", I just don't think that using django just for project storage is worth it! You haven't said what you think of my plan - why do not like it? And let's get @PullJosh's approval before we do anything - this is HIS project after all!

**Comment by matthewr6** [comment]
We're basically doing the exact same thing, but with much more control over who saves what and the ability to save (and possibly share, later) projects.

How exactly does Django detract?  I've never gotten a clear answer.

**Comment by BookOwl** [comment]
Also, if we use azure, we can get user authentication for free!

**Comment by quat1024** [comment]
I love that plan, it makes the most sense to me :+1: glad we could reach an understanding.
- repo A) Static HTML site with the editor, created with pure HTML, CSS, JS, and images.
- repo B) Python, Django, and other server stuff. When the editor is finished, it's pasted in, and "Share" features are added in. In later stages, invite front-end guys on to it to design the community portal.

How about `elemental-online` for the name? :P

**Comment by matthewr6** [comment]
Django and Heroku are free for our needs, @BookOwl 
@quat1024 Just a gh-pages branch, so we go to http://elementalcode.github.io/elemental, maybe?
btw, I hope you mean "share", or else I have no idea what you're talking about :P
Also, love your expansion of the idea :)  but both things are online, so...?
Have to go for now, but will respond to anything tomorrow.

**Comment by quat1024** [comment]
Haha forgot about gh-pages. Went ahead and made one, I'll get it set up for us front-end weirdos

**Comment by BookOwl** [comment]
1. It is difficult to get running for us to test/use/create. 
2. It seems to add a lot if overhead for "just" project storage when we can do the same thing without it. 
3. A lot of us don't want to use it and/or don't know how. If nobody wants to use it, and we have to use it anyway, you are going to have unhappy developers! 
4. We have to find a server to run it on.
5. It seems to make a mess of the code. 
   The other front-end devs could probably think of some more.
   Also, I REALLY don't think we should split this into two separate apps.

In the morning, I will create a new issue for everybody to hash this out in.

**Comment by BookOwl** [comment]
Who are you talking to when you say that you hope they meant "share"? When I was talking about sharing, I meant like how scratch does.

**Comment by quat1024** [comment]
^ It was my typo, I typoed share as shure or something

**Comment by BookOwl** [comment]
Who's expansion of what idea? (Sorry if it's obvious, it's 11:15 PM and I am really tired)
Oh, and just so you know, azure is free if we don't generate much traffic.

**Comment by BookOwl** [comment]
OK

**Comment by matthewr6** [comment]
quat1024's expansion, and Heroku is also free if we don't have too much traffic :P

**Pull request merged**
