### PR TITLE
Better New-File Dialog

### PR DESCRIPTION
**Pull request by mrjacobbloom**
See #218

### CODE REVIEW

**Comment by TheInitializer** [comment]
Ooh, this is being implemented! I'll check it out.

**Review by TheInitializer — DISMISSED** [review]
looks good, seems to work. It's not draggable or anything but I don't think that matters and I don't know how to do that. I'd add `cursor: pointer` to `.add-file` though.

**Comment by mrjacobbloom** [comment]
> I'd add `cursor: pointer` to `.add-file` though.

Good idea, I hadn't styled `.add-file` at all in this PR but now does seem like a good time to get around to it

**Comment by mrjacobbloom** [comment]
I updated the file pane to use the same styles as the new file popup (which includes hover styles and `cursor: pointer`)
screen shot 2017-05-08 at 9 50 59 pm

**Comment by mrjacobbloom** [comment]
sorry I'm new to these review things and idk if I was just supposed to do that--I'd just like someone's go-ahead before merging this in

**Comment by matthewr6** [comment]
idk but it seems right

**Comment by mrjacobbloom** [comment]
ok I got a thumbs-up reaction. that seems good enough

**Comment by towerofnix** [comment]
screen shot 2017-05-10 at 1 46 16 pm

"MY AWESOME



DOCUMENT.html"

(This probably belongs in a new issue.)

**Comment by mrjacobbloom** [comment]
welp xD

**Pull request merged**
