### PR TITLE
Preserved some gh-pages changes with block-editor-intuitive-trash

### PR DESCRIPTION
**Pull request by iamunknown2**

### CODE REVIEW

**Comment by matthewr6** [comment]
yay will look tomorrow if I have internet access

**Comment by iamunknown2** [comment]
Uh... Firedrake?

**Comment by matthewr6** [comment]
I've been on vacation for the past week

**Comment by iamunknown2** [comment]
Oh.

**Comment by matthewr6** [comment]
I haven't tested, so please don't break

**Comment by towerofnix** [comment]
+untested-code? :P

(oh wait, is that that tag part only part of opensprites? whatever, make one? :package:)

**Comment by matthewr6** [comment]
(feel free)

**Pull request merged**
