### PR TITLE
userselect

### PR DESCRIPTION
**Pull request by OrangeBacon**
no user select anywhere in body except text input

### CODE REVIEW

**Comment by matthewr6** [comment]
Does this still allow you to select text on contenteditables?

**Comment by OrangeBacon** [comment]
I think so, the add attribute to div still works ...

**Comment by matthewr6** [comment]
Could you test it to make sure?
Thanks.

**Comment by OrangeBacon** [comment]
Yes, I have checked it, I can type in the add attribute and the text content of blocks and the value of the attributes.  I don't think it effects text areas.

**Comment by matthewr6** [comment]
I mean can you _select text_ in text contents of blocks?

**Comment by OrangeBacon** [comment]
Yes

**Comment by matthewr6** [comment]
@ScratchOs Please make a pull request into `block-editor`.

**Pull request merged**
