### PR TITLE
Rework blocks

### PR DESCRIPTION
**Pull request by matthewr6**

### CODE REVIEW

**Comment by matthewr6** [comment]
Previously #249

**Comment by mrjacobbloom** [comment]
Good, thank you

**Comment by mrjacobbloom** [comment]
@Firedrake969 I can't request a review because this PR belongs to you but please review

**Comment by matthewr6** [comment]
Ok once I get home

**Review by matthewr6 — COMMENTED** [review]
looks good

**Comment by mrjacobbloom** [comment]
Yay :D

**Pull request merged**
