### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by matthewr6**
find a way to censor stuff, maybe?  assigning this to you @Dylan5797 so you can figure out a way to censor stuff

### CODE REVIEW

**Comment by PolyEdge** [comment]
Aww the build failed. What do you mean by censor stuff?

**Comment by matthewr6** [comment]
Profanity filtering....
crap I'll fix the test stuff

**Comment by matthewr6** [comment]
Fixed the tests

**Comment by PolyEdge** [comment]
Ok, I'll write a filter. Python or JS?

**Comment by PolyEdge** [comment]
Assuming python for backend :P

**Comment by matthewr6** [comment]
Python.

**Comment by matthewr6** [comment]
Really should start using feature or bug branches...

**Pull request merged**
